[project]
name = "mizukirobot-raspi"
version = "0.1.0"
description = "Robot control system for Raspberry Pi with neural network-based controllers"
authors = [
    { name = "Yuma", email = "your-email@example.com" },
]
requires-python = ">=3.9"  # ラズパイOSでより現実的
dependencies = [
    # 基本的な科学計算ライブラリ（システムパッケージ推奨）
    "numpy>=1.19.0",  # より緩い要件
    "scipy>=1.7.0",
    "scikit-learn>=1.0.0",
    "joblib>=1.0.0",
    "matplotlib>=3.3.0",
    "pandas>=1.3.0",
    
    # ラズパイ用ハードウェア制御
    "RPi.GPIO>=0.7.1; platform_machine=='aarch64'",
    "gpiozero>=1.6.0; platform_machine=='aarch64'",
    "pyserial>=3.5",
    
    # 軽量版の追加ライブラリ（条件付き）
    "tomli>=1.2.0; python_version < '3.11'",
]

[dependency-groups]
dev = [
    "pytest>=6.0.0",  # より緩い要件
    "ruff>=0.1.0",
]

# オプション: 重いパッケージは別グループ
desktop-only = [
    "pyplotutil",
    "scienceplots>=2.1.1",
    "pypdf>=3.0.0",
    "jupyter>=1.0.0",
]

[tool.ruff]
line-length = 88
target-version = "py39"  # Python 3.9対応

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]  # 行長制限を緩める

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

# ラズパイ用の追加設定
[tool.hatch.metadata]
allow-direct-references = false  # より安全